# Generated by Django 5.2.1 on 2025-05-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='centro',
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria'),
        ),
        migrations.AddField(
            model_name='evento',
            name='centro_cultural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.centrocultural'),
        ),
    ]
