# Generated by Django 5.2.1 on 2025-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_evento_categorias_remove_evento_centro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
