# Generated by Django 5.2.1 on 2025-07-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_centrocultural_ubicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="centrocultural",
            name="horario_apertura",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="centrocultural",
            name="horario_cierre",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="horario_apertura",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="horario_cierre",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
